cambio a español

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,12 +8,19 @@ on:
     pull_request:
       - main
 
-
 workflows:
   build_test:
     jobs:
-      - build_and_test:
+      - build_and_test
+      - runner-test
+      - push:
           context: env #contexto para variables de entorno
+          requires:
+            - build_and_test
+          filters:
+            branches:
+              only:
+                - main
   schedule:
     triggers:
       - schedule:
@@ -24,23 +31,20 @@ workflows:
                 - main
     jobs:
       - build_and_test
-  build_and_deploy:
-    jobs:
-      - build_and_test
-      - deploy:
-          requires:
-            - build_and_test
-          filters:
-            branches:
-              only: main
+  #build_and_deploy:
+  #  jobs:
+  #    - build_and_test
+  #    - deploy:
+  #        requires:
+  #          - build_and_test
+  #        filters:
+  #          branches:
+  #            only: main
 
 jobs:
   build_and_test:
     docker:
-      - image: sagonzalezn/vagrant-node:v1.1
-        auth:
-          username: $DOCKERHUB_USERNAME
-          password: $DOCKERHUB_PASSWORD
+      - image: node:12-alpine
     steps:
       - checkout
       - setup_remote_docker:
@@ -54,6 +58,48 @@ jobs:
       - run:
           name: Run Confirmation Message
           command: echo "All tests passed :D"
+
+  push:
+    docker:
+      - image: node:12-alpine
+    steps:
+      - checkout
+      - setup_remote_docker:
+          docker_layer_caching: true
+      - run:
+          name: Install docker
+          command: apk add docker
+      - run:
+          name: Debug Information
+          command: |
+            # Check the contents of VERSION.txt and its format
+            echo "Listing files and their contents:"
+            ls -la
+            cat VERSION.txt || echo "VERSION.txt file is missing or empty"
+      - run:
+          name: Build Docker image
+          command: |
+            TAG=$(cat VERSION.txt)
+            echo "New version is: $TAG"
+            if [[ -z "$TAG" || "$TAG" =~ [^a-zA-Z0-9._-] ]]; then
+              echo "Invalid Docker tag format: $TAG"
+              exit 1
+            fi
+            # Build the Docker image
+            docker build -t sagonzalezn/vagrant-node:${TAG} ./app
+      - run:
+          name: Push Docker image to dockerhub
+          command: |
+            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
+            docker push sagonzalezn/vagrant-node:1.1.3
+            docker tag sagonzalezn/vagrant-node:1.1.3 sagonzalezn/vagrant-node:latest
+            docker push sagonzalezn/vagrant-node:latest
+
+  runner-test:
+    machine: true
+    resource_class: run/test3
+    steps:
+      - run: echo "Hi I'm on Runners!"
   
   deploy:
     docker:
@@ -65,7 +111,11 @@ jobs:
       - run:
           name: Deploy Containers to Vagrant Machine
           command: |
-            ssh -o StrictHostChecking=no vagrant@192.168.0.16 '
+            apt update
+            apt install openssh-client -y
+            apt install net-tools
+            ifconfig
+            ssh -o StrictHostKeyChecking=no vagrant@$SSH_CONNECTION '
               docker compose -f /vagrant/docker-compose.yml pull
 
               docker compose -f /vagrant/docker-compose.yml up -d --build
